'use client';

import React, { useState } from 'react';
import { RecipeResponse } from '@/lib/types';
import {
  ChefHat,
  Clock,
  Users,
  Flame,
  CheckCircle2,
  Copy,
  Check,
  Download,
  Printer,
  Heart,
  Share2,
  Lightbulb,
  AlertTriangle,
  RotateCcw,
  Sparkles
} from 'lucide-react';

interface RecipeCardProps {
  recipe: RecipeResponse;
  onClear?: () => void;
  isFavorite?: boolean;
  onToggleFavorite?: () => void;
}

export const RecipeCard: React.FC<RecipeCardProps> = ({
  recipe,
  onClear,
  isFavorite = false,
  onToggleFavorite,
}) => {
  const [completedSteps, setCompletedSteps] = useState<number[]>([]);
  const [checkedIngredients, setCheckedIngredients] = useState<number[]>([]);
  const [copied, setCopied] = useState<boolean>(false);

  const toggleStep = (index: number) => {
    setCompletedSteps((prev) =>
      prev.includes(index) ? prev.filter((i) => i !== index) : [...prev, index]
    );
  };

  const toggleIngredient = (index: number) => {
    setCheckedIngredients((prev) =>
      prev.includes(index) ? prev.filter((i) => i !== index) : [...prev, index]
    );
  };

  const handleCopyRecipe = async () => {
    const formattedText = `
=== ${recipe.recipeName.toUpperCase()} ===
Cuisine: ${recipe.cuisine} | Dietary: ${recipe.dietaryTag} | Servings: ${recipe.servings}
Prep Time: ${recipe.prepTime} | Cook Time: ${recipe.cookTime} | Calories: ${recipe.estimatedCalories}

SUMMARY:
${recipe.summary}

INGREDIENTS:
${recipe.ingredients
  .map((ing) => (typeof ing === 'string' ? `- ${ing}` : `- ${ing.item}${ing.amount ? ` (${ing.amount})` : ''}`))
  .join('\n')}

${recipe.missingIngredients && recipe.missingIngredients.length > 0 ? `MISSING/OPTIONAL ITEMS:\n${recipe.missingIngredients.map(m => `- ${m}`).join('\n')}\n` : ''}
INSTRUCTIONS:
${recipe.instructions.map((step, idx) => `${idx + 1}. ${step}`).join('\n')}

COOKING TIPS:
${recipe.cookingTips.map((tip) => `- ${tip}`).join('\n')}

ESTIMATED NUTRITION (PER SERVING):
Calories: ${recipe.nutrition?.calories || recipe.estimatedCalories} | Protein: ${recipe.nutrition?.protein || 'N/A'} | Carbs: ${recipe.nutrition?.carbs || 'N/A'} | Fat: ${recipe.nutrition?.fat || 'N/A'}
`.trim();

    try {
      await navigator.clipboard.writeText(formattedText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy text', err);
    }
  };

  const handleDownloadTxt = () => {
    const formattedText = `
=== ${recipe.recipeName.toUpperCase()} ===
Generated by AI Recipe Generator

CUISINE: ${recipe.cuisine}
DIETARY: ${recipe.dietaryTag}
SERVINGS: ${recipe.servings} Person(s)
PREP TIME: ${recipe.prepTime}
COOK TIME: ${recipe.cookTime}
CALORIES: ${recipe.estimatedCalories}

SUMMARY:
${recipe.summary}

INGREDIENTS:
${recipe.ingredients
  .map((ing) => (typeof ing === 'string' ? `- ${ing}` : `- ${ing.item}${ing.amount ? ` (${ing.amount})` : ''}`))
  .join('\n')}

INSTRUCTIONS:
${recipe.instructions.map((step, idx) => `${idx + 1}. ${step}`).join('\n')}

COOKING TIPS:
${recipe.cookingTips.map((tip) => `- ${tip}`).join('\n')}
`.trim();

    const blob = new Blob([formattedText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${recipe.recipeName.toLowerCase().replace(/[^a-z0-0]+/g, '_')}_recipe.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div
      id="recipe-card-container"
      className="bg-white dark:bg-slate-900 rounded-3xl border border-orange-200/80 dark:border-slate-800 shadow-xl overflow-hidden print:shadow-none print:border-none print:p-0 transition-all"
    >
      {/* Top Banner Header */}
      <div className="bg-gradient-to-r from-orange-600 via-amber-500 to-orange-500 text-white p-6 sm:p-8 space-y-4 relative">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/20 backdrop-blur-md text-xs font-extrabold uppercase tracking-wider text-white">
            <Sparkles className="w-3.5 h-3.5" />
            <span>AI Master Chef Creation</span>
          </div>

          {/* Action Tools */}
          <div className="flex items-center gap-2 print:hidden">
            {onToggleFavorite && (
              <button
                type="button"
                id="favorite-recipe-btn"
                onClick={onToggleFavorite}
                className={`p-2.5 rounded-2xl transition-all cursor-pointer ${
                  isFavorite
                    ? 'bg-rose-500 text-white shadow-md'
                    : 'bg-white/20 text-white hover:bg-white/30'
                }`}
                title={isFavorite ? 'Remove from favorites' : 'Save to favorites'}
              >
                <Heart className={`w-5 h-5 ${isFavorite ? 'fill-white' : ''}`} />
              </button>
            )}

            <button
              type="button"
              id="copy-recipe-btn"
              onClick={handleCopyRecipe}
              className="p-2.5 rounded-2xl bg-white/20 hover:bg-white/30 text-white transition-all cursor-pointer flex items-center gap-1.5 text-xs font-bold"
              title="Copy recipe text"
            >
              {copied ? <Check className="w-4 h-4 text-emerald-300" /> : <Copy className="w-4 h-4" />}
              <span className="hidden sm:inline">{copied ? 'Copied!' : 'Copy'}</span>
            </button>

            <button
              type="button"
              id="download-recipe-btn"
              onClick={handleDownloadTxt}
              className="p-2.5 rounded-2xl bg-white/20 hover:bg-white/30 text-white transition-all cursor-pointer text-xs font-bold flex items-center gap-1.5"
              title="Download TXT file"
            >
              <Download className="w-4 h-4" />
              <span className="hidden sm:inline">Export</span>
            </button>

            <button
              type="button"
              id="print-recipe-btn"
              onClick={handlePrint}
              className="p-2.5 rounded-2xl bg-white/20 hover:bg-white/30 text-white transition-all cursor-pointer text-xs font-bold"
              title="Print recipe"
            >
              <Printer className="w-4 h-4" />
            </button>

            {onClear && (
              <button
                type="button"
                id="clear-recipe-view-btn"
                onClick={onClear}
                className="p-2.5 rounded-2xl bg-white/20 hover:bg-white/30 text-white transition-all cursor-pointer"
                title="Close Recipe"
              >
                <RotateCcw className="w-4 h-4" />
              </button>
            )}
          </div>
        </div>

        <div className="space-y-2">
          <h2 className="text-2xl sm:text-4xl font-black text-white tracking-tight">
            {recipe.recipeName}
          </h2>
          <p className="text-orange-50/90 text-sm sm:text-base leading-relaxed max-w-3xl">
            {recipe.summary}
          </p>
        </div>

        {/* Quick Recipe Badges */}
        <div className="flex flex-wrap gap-2 pt-2">
          <span className="px-3 py-1 rounded-xl bg-white/15 backdrop-blur-xs text-xs font-bold text-white border border-white/20">
            🌍 {recipe.cuisine} Cuisine
          </span>
          <span className="px-3 py-1 rounded-xl bg-white/15 backdrop-blur-xs text-xs font-bold text-white border border-white/20">
            🥗 {recipe.dietaryTag}
          </span>
          <span className="px-3 py-1 rounded-xl bg-white/15 backdrop-blur-xs text-xs font-bold text-white border border-white/20">
            ⚡ {recipe.difficulty || 'Easy'} Level
          </span>
        </div>
      </div>

      {/* Stats Bar */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 p-6 bg-slate-50 dark:bg-slate-800/50 border-b border-slate-100 dark:border-slate-800">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-orange-100 dark:bg-orange-950/80 text-orange-600 dark:text-orange-400 flex items-center justify-center font-bold">
            <Clock className="w-5 h-5" />
          </div>
          <div>
            <div className="text-xs text-slate-500 dark:text-slate-400 font-medium">Prep Time</div>
            <div className="text-sm font-extrabold text-slate-800 dark:text-slate-100">{recipe.prepTime}</div>
          </div>
        </div>

        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-amber-100 dark:bg-amber-950/80 text-amber-600 dark:text-amber-400 flex items-center justify-center font-bold">
            <ChefHat className="w-5 h-5" />
          </div>
          <div>
            <div className="text-xs text-slate-500 dark:text-slate-400 font-medium">Cook Time</div>
            <div className="text-sm font-extrabold text-slate-800 dark:text-slate-100">{recipe.cookTime}</div>
          </div>
        </div>

        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-blue-100 dark:bg-blue-950/80 text-blue-600 dark:text-blue-400 flex items-center justify-center font-bold">
            <Users className="w-5 h-5" />
          </div>
          <div>
            <div className="text-xs text-slate-500 dark:text-slate-400 font-medium">Portion Yield</div>
            <div className="text-sm font-extrabold text-slate-800 dark:text-slate-100">{recipe.servings} Servings</div>
          </div>
        </div>

        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-rose-100 dark:bg-rose-950/80 text-rose-600 dark:text-rose-400 flex items-center justify-center font-bold">
            <Flame className="w-5 h-5" />
          </div>
          <div>
            <div className="text-xs text-slate-500 dark:text-slate-400 font-medium">Estimated Energy</div>
            <div className="text-sm font-extrabold text-slate-800 dark:text-slate-100">{recipe.estimatedCalories}</div>
          </div>
        </div>
      </div>

      {/* Main Recipe Body Grid */}
      <div className="p-6 sm:p-8 grid grid-cols-1 lg:grid-cols-3 gap-8">
        
        {/* Ingredients Column */}
        <div className="space-y-6 lg:col-span-1">
          <div className="space-y-1 border-b border-slate-100 dark:border-slate-800 pb-3">
            <h3 className="text-xl font-extrabold text-slate-900 dark:text-white flex items-center gap-2">
              <ChefHat className="w-5 h-5 text-orange-600 dark:text-orange-500" />
              Ingredients Needed
            </h3>
            <p className="text-xs text-slate-500 dark:text-slate-400">
              Tap items as you assemble your prep station:
            </p>
          </div>

          <ul className="space-y-2.5">
            {recipe.ingredients.map((ing, idx) => {
              const itemText = typeof ing === 'string' ? ing : ing.item;
              const amountText = typeof ing === 'string' ? '' : ing.amount;
              const isChecked = checkedIngredients.includes(idx);

              return (
                <li
                  key={idx}
                  onClick={() => toggleIngredient(idx)}
                  className={`p-3 rounded-2xl border transition-all cursor-pointer flex items-start gap-3 ${
                    isChecked
                      ? 'bg-slate-50 dark:bg-slate-800/40 border-slate-200 dark:border-slate-800 opacity-60 line-through'
                      : 'bg-orange-50/50 dark:bg-slate-800/80 border-orange-100 dark:border-slate-700/80 hover:bg-orange-100/50 dark:hover:bg-slate-700'
                  }`}
                >
                  <div
                    className={`w-5 h-5 rounded-lg border mt-0.5 flex items-center justify-center shrink-0 transition-colors ${
                      isChecked
                        ? 'bg-orange-600 border-orange-600 text-white'
                        : 'border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-900'
                    }`}
                  >
                    {isChecked && <CheckCircle2 className="w-3.5 h-3.5" />}
                  </div>
                  <div className="text-sm font-semibold text-slate-800 dark:text-slate-200 flex-1">
                    <span>{itemText}</span>
                    {amountText && (
                      <span className="block text-xs font-extrabold text-orange-600 dark:text-orange-400 mt-0.5">
                        {amountText}
                      </span>
                    )}
                  </div>
                </li>
              );
            })}
          </ul>

          {/* Missing or Optional Additions */}
          {recipe.missingIngredients && recipe.missingIngredients.length > 0 && (
            <div className="bg-amber-50 dark:bg-amber-950/40 border border-amber-200 dark:border-amber-900 rounded-2xl p-4 space-y-2">
              <div className="flex items-center gap-2 text-xs font-extrabold text-amber-800 dark:text-amber-300 uppercase tracking-wider">
                <AlertTriangle className="w-4 h-4 text-amber-600 dark:text-amber-400" />
                Optional / Pantry Recommendations
              </div>
              <ul className="space-y-1 text-xs text-amber-900 dark:text-amber-200 list-disc list-inside">
                {recipe.missingIngredients.map((m, idx) => (
                  <li key={idx}>{m}</li>
                ))}
              </ul>
            </div>
          )}

          {/* Nutrition Info Breakdown */}
          {recipe.nutrition && (
            <div className="bg-slate-50 dark:bg-slate-800/60 rounded-2xl p-4 border border-slate-200 dark:border-slate-700 space-y-3">
              <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">
                Nutritional Breakdown (Per Serving)
              </h4>
              <div className="grid grid-cols-2 gap-2 text-xs">
                <div className="bg-white dark:bg-slate-800 p-2.5 rounded-xl border border-slate-100 dark:border-slate-700">
                  <span className="text-slate-400 block text-[10px]">Calories</span>
                  <span className="font-extrabold text-slate-800 dark:text-slate-100">{recipe.nutrition.calories}</span>
                </div>
                <div className="bg-white dark:bg-slate-800 p-2.5 rounded-xl border border-slate-100 dark:border-slate-700">
                  <span className="text-slate-400 block text-[10px]">Protein</span>
                  <span className="font-extrabold text-slate-800 dark:text-slate-100">{recipe.nutrition.protein}</span>
                </div>
                <div className="bg-white dark:bg-slate-800 p-2.5 rounded-xl border border-slate-100 dark:border-slate-700">
                  <span className="text-slate-400 block text-[10px]">Carbohydrates</span>
                  <span className="font-extrabold text-slate-800 dark:text-slate-100">{recipe.nutrition.carbs}</span>
                </div>
                <div className="bg-white dark:bg-slate-800 p-2.5 rounded-xl border border-slate-100 dark:border-slate-700">
                  <span className="text-slate-400 block text-[10px]">Fats</span>
                  <span className="font-extrabold text-slate-800 dark:text-slate-100">{recipe.nutrition.fat}</span>
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Cooking Steps Column */}
        <div className="space-y-6 lg:col-span-2">
          <div className="flex items-center justify-between border-b border-slate-100 dark:border-slate-800 pb-3">
            <div>
              <h3 className="text-xl font-extrabold text-slate-900 dark:text-white flex items-center gap-2">
                <ChefHat className="w-5 h-5 text-orange-600 dark:text-orange-500" />
                Step-by-Step Cooking Guide
              </h3>
              <p className="text-xs text-slate-500 dark:text-slate-400">
                Check off each step as you complete it:
              </p>
            </div>
            {completedSteps.length > 0 && (
              <span className="text-xs font-bold px-3 py-1 rounded-full bg-emerald-100 dark:bg-emerald-950/80 text-emerald-700 dark:text-emerald-300">
                {completedSteps.length} of {recipe.instructions.length} done
              </span>
            )}
          </div>

          <div className="space-y-4">
            {recipe.instructions.map((step, idx) => {
              const isDone = completedSteps.includes(idx);

              return (
                <div
                  key={idx}
                  onClick={() => toggleStep(idx)}
                  className={`p-4 sm:p-5 rounded-2xl border transition-all cursor-pointer flex gap-4 ${
                    isDone
                      ? 'bg-slate-50 dark:bg-slate-800/30 border-slate-200 dark:border-slate-800 opacity-60'
                      : 'bg-white dark:bg-slate-900 border-slate-200 dark:border-slate-800 hover:border-orange-300 dark:hover:border-slate-700 hover:shadow-md'
                  }`}
                >
                  <div
                    className={`w-8 h-8 rounded-xl shrink-0 flex items-center justify-center font-black text-sm transition-colors ${
                      isDone
                        ? 'bg-emerald-500 text-white'
                        : 'bg-orange-100 dark:bg-orange-950/80 text-orange-700 dark:text-orange-300'
                    }`}
                  >
                    {isDone ? <CheckCircle2 className="w-5 h-5" /> : idx + 1}
                  </div>

                  <div className="space-y-1 flex-1">
                    <p
                      className={`text-sm sm:text-base leading-relaxed font-medium ${
                        isDone
                          ? 'line-through text-slate-500 dark:text-slate-400'
                          : 'text-slate-800 dark:text-slate-100'
                      }`}
                    >
                      {step}
                    </p>
                  </div>
                </div>
              );
            })}
          </div>

          {/* Cooking Secrets & Chef Tips */}
          {recipe.cookingTips && recipe.cookingTips.length > 0 && (
            <div className="bg-orange-50/80 dark:bg-slate-800/80 border border-orange-200/80 dark:border-slate-700 rounded-3xl p-6 space-y-3">
              <h4 className="text-sm font-extrabold text-orange-900 dark:text-orange-300 flex items-center gap-2">
                <Lightbulb className="w-4 h-4 text-orange-600 dark:text-orange-400" />
                Chef's Pro Tips & Flavor Enhancers
              </h4>
              <ul className="space-y-2">
                {recipe.cookingTips.map((tip, idx) => (
                  <li key={idx} className="text-xs sm:text-sm text-slate-700 dark:text-slate-300 flex items-start gap-2">
                    <span className="text-orange-500 font-bold">•</span>
                    <span>{tip}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}

        </div>

      </div>
    </div>
  );
};
